name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Clone & Building
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            rm -rf /var/www/github-actions/*
            cd /var/www/github-actions
            git clone git@github.com:omwro/PortfolioVue.git
            cd PortfolioVue
            npm install
            npm run build

  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            rm -rf /var/www/omererdem/index/*
            mv /var/www/github-actions/PortfolioVue/dist /var/www/omererdem/index